#!/bin/bash
#watch -n 0 "lscpu | grep 'MHz'"

state=$( cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor )
newState=""
stringState="Now in *** "
echo "	            The current state is [ $state ]"
if [ $state == "ondemand" ] 
then
    echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    newState=$( cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor )	
else
    echo ondemand | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    newState=$( cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor )
fi
#watch -n 0 "lscpu | grep 'MHz'"
echo "			Now in *** $newState ***mode"